
volumes:
  forgejo-data:
  forgejo-runner-data:

services:
  app:
    volumes:
      - type: volume
        source: forgejo-data
        target: /data

  runner:
    volumes:
      - type: volume
        source: forgejo-runner-data
        target: /data
