
services:
  app:
    volumes:
      - type: bind
        source: ./volumes/forgejo/app
        target: /data
        bind:
          create_host_path: true

  runner:
    volumes:
      - type: bind
        source: ./volumes/forgejo/runner
        target: /data
        bind:
          create_host_path: true
